version: "3.3"
services:
  dev-start:
    build: 
      context: ./dockerfiles/dev-start
    image: dev-start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
  storybook:
    build:
      context: ./dockerfiles/dev-start
    image: storybook
    ports:
      - "9009:9009"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
